#!/bin/bash

#Create logfile
rm -rf logPhase1.txt
touch logPhase1.txt

#Copy create + insert to node
cat create.sql | kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cat > create.sql"
cat insert.sql | kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cat > insert.sql"

#Check status of nodes
kubectl get pods -n thesis-crdb | grep 'cockroachdb-0\|cockroachdb-1\|cockroachdb-2\|NAME' >> logPhase1.txt

#Create table in node
kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cat create.sql | cockroach sql --insecure"

echo "Beginning phase 1" >> logPhase1.txt

echo "DELETING NODE" >> logPhase1.txt
#Stop node
kubectl delete pod/k8crdb-cockroachdb-1 -n thesis-crdb >> logPhase1.txt

#Check status of nodes
echo "STATUS" >> logPhase1.txt
kubectl get pods -n thesis-crdb | grep 'cockroachdb-0\|cockroachdb-1\|cockroachdb-2\|NAME' >> logPhase1.txt

echo "INSERTING 500 ROWS" >> logPhase1.txt
#run insert.sql in node (insert rows)
kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cat insert.sql | cockroach sql --insecure"
echo "DONE INSERTING 500 ROWS" >> logPhase1.txt

#Check status of nodes
echo "STATUS" >> logPhase1.txt
kubectl get pods -n thesis-crdb | grep 'cockroachdb-0\|cockroachdb-1\|cockroachdb-2\|NAME' >> logPhase1.txt &

#Insert rows
for i in {1..3}
do
    echo "INSERTING 500 ROWS" >> logPhase1.txt
  
    #run insert.sql in node (insert rows)
    kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cat insert.sql | cockroach sql --insecure"
    echo "DONE INSERTING 500 ROWS" >> logPhase1.txt
  
    echo "NR OF ROWS INSERTED: $((500*i))" >> logPhase1.txt
done


echo "ALL ROWS INSERTED" >> logPhase1.txt

echo "STATUS" >> logPhase1.txt
#Check status of nodes
kubectl get pods -n thesis-crdb | grep 'cockroachdb-0\|cockroachdb-1\|cockroachdb-2\|NAME' >> logPhase1.txt

echo "COUNTING ROWS" >> logPhase1.txt
#Count nr of inserted rows and save in logPhase1.txt
kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cockroach sql --insecure --execute='select count_rows() from student;'" >> logPhase1.txt

echo "Check id = 254" >> logPhase1.txt
kubectl exec -i -n thesis-crdb service/k8crdb-cockroachdb-public -- bash -c "cockroach sql --insecure --execute='select count_rows() from student where id <= 254 ;'" >> logPhase1.txt

echo "End of phase one" >> logPhase1.txt